REQUIRED_FIELDS = {
    "request_id",
    "title",
    "track_sector",
    "work_type",
    "duration_minutes",
    "earliest_start",
    "deadline",
    "priority",
}

DEFAULT_FIELD_MAPPING = {
    "Request ID": "request_id",
    "Job ID": "request_id",
    "Title": "title",
    "Line Section": "track_sector",
    "Track Sector": "track_sector",
    "Work Type": "work_type",
    "Duration": "duration_minutes",
    "Duration Minutes": "duration_minutes",
    "Earliest Start": "earliest_start",
    "Start Window": "earliest_start",
    "Deadline": "deadline",
    "Due Time": "deadline",
    "Priority": "priority",
    "Crew": "required_crew",
    "Required Crew": "required_crew",
    "Equipment": "required_equipment",
    "Required Equipment": "required_equipment",
    "Dependencies": "dependencies",
    "Incompatible Work Types": "incompatible_work_types",
    "Approval Status": "approval_status",
    "Locked": "locked",
    "Fixed Start": "fixed_start",
    "Fixed End": "fixed_end",
    "Created By": "created_by",
    "Requester": "created_by",
    "Notes": "notes",
}
